---
title: "Syllabus"
---

## Course Information

Course: AREC 493

Instructor: Dr. Gaby Perez-Quesada

Email: [gperezqu\@utk.edu](mailto:gperezqu@utk.edu)

Term: Spring 2026

Times: T & R, 2:30-3:45pm

Location: Morgan Hall 212B

Office Hours: T & R, 3:45-5:00pm

## Learning Objectives

-   Use R and ***tidyverse*** tools to import, clean, and manipulate spatial data efficiently and reproducibly
-   Explain and apply core GIS concepts, including spatial data types, projections, and coordinate reference systems
-   Work with vector and raster datasets, performing basic operations, analysis, and integration between data types
-   Visualize spatial data effectively through maps to identify and interpret spatial patterns
-   Access and process real-world spatial datasets from public sources for applied economic analysis

## Prerequisites

AREC 270. Prior coursework in basic statistics or econometrics is recommended. Students should be comfortable with fundamental concepts such as descriptive statistics, regression analysis, and interpreting empirical results.

## Lecture Topics

(*Subject to change based on progression through the material*)

**Getting started with R**

-   Get started with running code
-   Install and load libraries
-   Load in data from files, the internet, or libraries
-   Write good code and responsibly use AI in your coding
-   Look at your data and get basic statistical results
-   Manipulate your data and get it ready for analysis

**GIS fundamentals**

-   Types of spatial data
-   Projections and coordinate reference system

**The basics of vector data handling using *sf* package**

-   Vector data (points, lines, polygons)
-   Import and export vector data
-   (re)projection of spatial datasets
-   Single-layer geometrical operations (e.g., create buffers)

**Spatial interactions of vector datasets**

-   Understand topological relations of multiple *sf* objects
-   Spatially subset a layer based on another layer
-   Extracting values form one layer to another layer

**The basics of raster data handling using *raster* and *terra* packages**

-   Import and export raster data
-   Stack raster data
-   Quick plotting

**Spatial interactions of vector and raster datasets**

-   Cropping a raster layer to the geographic extent of a vector layer
-   Extracting values form a raster to a vector later

**Creating maps using *ggplot2* package**

-   Visualizing spatial data with ggplot2

**Download and process publicly available datasets**

-   USDA NASS QuickStat (*tidyUSDA*)
-   PRISM (*prism*)
-   Daymet (*daymetr*)
-   Cropland Data Layer (*CropScapeR*)
-   Census (*tidycensus*)

## Course Materials

This course will follow a set of high-quality, freely available online resources, alongside DataCamp Classroom. Students are encouraged to consult these materials to complement lectures and exercises.

**Introduction to R**

-   [R for Data Science](https://r4ds.hadley.nz)
-   [Introduction to Working with Data: R version](https://nickchk.com/Coding%20and%20Data%20Cleaning%20Intro%20R.html)

**R for GIS**

-   [R as GIS for Economists](https://tmieno2.github.io/R-as-GIS-for-Economists-Quarto/)
-   [Spatial Statistics for Data Science: Theory and Practice with R](https://www.paulamoraga.com/book-spatial/index.html)

## Grading

Assignments: 30%

Midterm Exam: 25%

Participation: 15%

Final Project: 30%

## Academic Integrity

In accordance with the college’s academic honesty policy, students are expected to submit original work for all assignments. Any form of academic dishonesty will not be tolerated. Plagiarism includes copying answers, phrases, sentence structures, or ideas from any source without proper attribution.

This also applies to the use of artificial intelligence tools such as ChatGPT. While you may use AI to assist with coding or to explore solutions, you must not simply feed it questions and submit the generated responses as your own work. All submitted assignments should reflect your understanding and effort.

## Generative AI Tools in Coursework

Open Use Guidelines: Embrace and encourage AI use in assignments, with the requirement that students disclose any AI assistance.

*AI policy: permitted in this course with attribution*

In this course, students are allowed to use Generative AI Tools like ChatGPT to support their work. To maintain academic integrity, students must disclose any AI-generated material they use and properly attribute it, including in-text citations, quotations, and references.

A student should include the following statement in assignments to indicate use of a Generative AI Tool: “The author(s) would like to acknowledge the use of \[Generative AI Tool Name\], a language model developed by \[Generative AI Tool Provider\], in the preparation of this assignment. The \[Generative AI Tool Name\] was used in the following way(s) in this assignment \[e.g., coding, brainstorming, grammatical correction, citation, which portion of the assignment\].”

## Accommodations for Students with Disabilities

I am available to discuss appropriate academic accommodations that may be required for student with disabilities. The University of Tennessee, Knoxville, is committed to providing an inclusive learning environment for all students. If you anticipate or experience a barrier in this course due to a chronic health condition, a learning, hearing, neurological, mental health, vision, physical, or other kind of disability, or a temporary injury, you are encouraged to contact Student Disability Services (SDS) at 865-974-6087 or [sds\@utk.edu](mailto:sds@utk.edu). An SDS Coordinator will meet with you to develop a plan to ensure you have equitable access to this course. If you are already registered with SDS, please contact your instructor to discuss implementing accommodations included in your course access letter.

## Online\@UT

Students are required to routinely access their UTK email account and the course website located on the Online\@UT (Canvas) portal
