---
title: "Getting Started with R"
---

## Why use R?

As stated on the [R Project website](https://www.r-project.org), R is a programming language and environment for statistical computing and graphics. It’s flexible, easy to build on, and supported by a large, welcoming community.

**Cost**

R is free and open-source for everyone.

**Reproducibility**

Using a programming language for data management and analysis, rather than relying on Excel or other point-and-click tools, makes your work easier to reproduce, helps you catch mistakes more quickly, and can save you a lot of time and effort.

**Community**

The R community is huge and supportive. New packages and tools to tackle real-world problems are developed all the time, and the community helps test, improve, and share them.

## Installation: R and RStudio

To get started, you’ll need to have R running on your computer. There are a few options, but **RStudio** is a popular choice that makes working with R much easier.

Installing RStudio takes two steps. First, you’ll need to install the R language itself.

**How to install R**

Visit this website <https://www.r-project.org> and download the latest version of R suitable for your computer. *Note*: Any mirror will work fine, but perhaps pick one close to you.

Once that's done, you can **install RStudio**

Go to this website <https://posit.co/download/rstudio-desktop/> and download the latest free Desktop version of RStudio suitable for your computer.

## Navigating RStudio

Open RStudio. RStudio is divided into four main *panes*, each showing different information like your code, console, and files.

**The source pane**

By default, this pane appears in the upper-left corner. It's where you can write, run, and save your scripts (your scripts are basically the sets of commands you want R to execute. You can also use this pane to view your datasets (data frames) while working.

**The R console pane**

The R Console (usually in the lower-left pane) is where the R "engine" lives. When you run commands here, you’ll see results, warnings, or error messages right away. You can type commands directly in the Console, but unlike scripts, these commands won’t be saved for later, so it’s best for quick tests or checks.

**The environment pane**

By default, this pane appears in the upper-right. It’s mainly used to get a quick look at the objects in your R environment during the current session. These objects can include datasets you’ve imported, created, or modified, as well as parameters or vectors and lists you’ve defined. You can click the little arrow next to a data frame to explore its variables.

**Plots, Viewer, Packages, and Help pane**

The lower-right pane contains several useful tabs. The *Plots* tab displays your charts, graphs, and maps, while the *Viewer* tab shows interactive or HTML outputs. The *Help* tab gives access to R documentation and help files, and the *Files* tab works like a mini file explorer, letting you open, move, or delete files. Finally, the *Packages* tab lets you see which R packages are installed, add new ones, update or remove them, and load or unload them for your session.

## Scripts

Scripts are a fundamental part of programming. They’re files that store the commands you want R to run, like creating or modifying datasets and generating visualizations. You can save a script and run it again later, which comes with some big advantages:

*Portability*: you can easily share your work with others by sending them your script.

*Reproducibility*: using scripts makes it clear exactly what steps you took, so you, or anyone else, can repeat your analysis with confidence.

*Example script*

```{r Example script}
3 + 4
a <- 3 + 4 # you can annotate around your code!
```

## Quarto

[Quarto](https://quarto.org/docs/get-started/hello/rstudio.html) is a tool that lets you combine your R code, text, and visualizations in a single document. It’s perfect for creating reports, tutorials, or assignments where you want your analysis and explanations to live side by side. With Quarto, you can run your code, include the results, and produce a polished document; all in one place, making your work easy to share and easy to reproduce.

*Free online resources*:

[Tutorial: Hello Quarto](https://quarto.org/docs/get-started/hello/rstudio.html)

[R for Data Science: Quarto](https://r4ds.hadley.nz/quarto.html)
